runtime: python
env: flex
instance_class: F1
runtime_config:
  python_version: 3.7
env_variables:
  CLOUD_SQL_USERNAME: postgres
  CLOUD_SQL_PASSWORD: "&2Pdd4zAp[>.8QDa"
  CLOUD_SQL_DATABASE_NAME: bravo_ai
  CLOUD_SQL_CONNECTION_NAME: bravo-ai-voice:asia-south1:bravo-instace
  STRIPE_PUBLISHABLE_KEY: pk_live_51MD76fSAyxbMUgOHK17Yw7hpwTeBBVWfuQGZYeAa9hKxxKCCImNFstOp45Jpe6ja2Pn9mxr981wu1bsDYkRCcPdI00HNagdCMQ
  STRIPE_SECRET_KEY: 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
  STRIPE_PRICE_ID: price_1MD7FMSAyxbMUgOHMO8onNf8
  STRIPE_PRICE_ID1: price_1MD7GxSAyxbMUgOHoxnI5Yav
  STRIPE_ENDPOINT_SECRET: whsec_j6VZcfjA9ljdElrUpTw77fKxGhhCdbo0
  REPLICATE_API_TOKEN: 32e56e6e80146f4301c4dd5dd7c50f9f6d941913
entrypoint: ./run.sh
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
  cpu_utilization:
    target_utilization: 0.6
beta_settings:
  cloud_sql_instances: bravo-ai-voice:asia-south1:bravo-instace
