runtime: python
env: flex
instance_class: F2
runtime_config:
  python_version: 3.7
env_variables:
  CLOUD_SQL_USERNAME: postgres
  CLOUD_SQL_PASSWORD: "&2Pdd4zAp[>.8QDa"
  CLOUD_SQL_DATABASE_NAME: bravo_ai
  CLOUD_SQL_CONNECTION_NAME: bravo-ai-voice:asia-south1:bravo-instace
entrypoint: ./run.sh
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
  cpu_utilization:
    target_utilization: 0.6
beta_settings:
  cloud_sql_instances: bravo-ai-voice:asia-south1:bravo-instace
