runtime: python
env: flex
instance_class: F1
runtime_config:
  python_version: 3.7
env_variables:
  CLOUD_SQL_USERNAME: postgres
  CLOUD_SQL_PASSWORD: "&2Pdd4zAp[>.8QDa"
  CLOUD_SQL_DATABASE_NAME: bravo_ai
  CLOUD_SQL_CONNECTION_NAME: bravo-ai-voice:asia-south1:bravo-instace
  STRIPE_PUBLISHABLE_KEY: pk_live_51M6WnuSFFYmekMFSz50FYtxHxxsedlxr3rChKOYBxnKQdgxLld29iDF11dDeeKsyIbJvTRf6mBYOFaRgCG1W5Lpa00J1ZIOiwe
  STRIPE_SECRET_KEY: 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
  STRIPE_PRICE_ID: price_1MBalXSFFYmekMFSu0ctEgWG
  STRIPE_PRICE_ID1: price_1MBcoxSFFYmekMFSdxRTmiCq
  STRIPE_ENDPOINT_SECRET: whsec_xFvHa9X2qGn1jRPdZwzE4E2BEPWq4iau
  REPLICATE_API_TOKEN: 32e56e6e80146f4301c4dd5dd7c50f9f6d941913
entrypoint: ./run.sh
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
  cpu_utilization:
    target_utilization: 0.6
beta_settings:
  cloud_sql_instances: bravo-ai-voice:asia-south1:bravo-instace
