runtime: python
env: flex
runtime_config:
  python_version: 3.7
env_variables:
  CLOUD_SQL_USERNAME: postgres
  CLOUD_SQL_PASSWORD: "&2Pdd4zAp[>.8QDa"
  CLOUD_SQL_DATABASE_NAME: bravo_ai
  CLOUD_SQL_CONNECTION_NAME: bravo-ai-voice:asia-south1:bravo-instace
entrypoint: gunicorn -c gunicorn.conf.py -b :8080 main:app --log-level=DEBUG --timeout=600 --t 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
beta_settings:
  cloud_sql_instances: bravo-ai-voice:asia-south1:bravo-instace
